---
version: '3.4'
services:
  api:
    build: { context: "../musicbox-api" }
    volumes: ["../musicbox-api:/app"]
    command: bin/wait-for-it.sh db:5432 -- passenger start -p 3000
    environment:
      DATABASE_URL: postgresql://postgres:postgrespassword@db
      REDIS_URL: redis://redis:6379
    links:
    - db
    - redis
    ports: ["3000:3000"]
  app:
    build: "."
    volumes:
    - ".:/app"
    - "/node_modules"
    command: npm start
    ports: ["8080:8080"]
  db:
    image: postgres:9.5.4
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports: ["5432:5432"]
  redis:
    image: redis:5.0.3
    ports: ["6379:6379"]
